import { defineConfig } from 'vite';
import { resolve } from 'path';

// CJS single-bundle build — for Node.js / CommonJS consumers (SSR, Jest, etc.).
// Runs after the main ESM build (emptyOutDir: false preserves dist/).
// Types are already generated by the main build; no dts plugin needed here.
export default defineConfig({
  build: {
    lib: {
      entry: resolve(__dirname, 'src/index.ts'),
      name: 'Eidos',
      formats: ['cjs'],
      fileName: () => 'eidos.cjs.js',
    },
    rollupOptions: {
      external: ['react', 'react-dom', 'react/jsx-runtime'],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
          'react/jsx-runtime': 'ReactJsxRuntime',
        },
      },
    },
    outDir: 'dist',
    emptyOutDir: false, // preserve ESM files from main build
    sourcemap: true,
    minify: 'esbuild',
  },
});
